apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: ce-p2
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  backend:
    serviceName: wordpress
    servicePort: 80
  # rules:
  # - http:
  #     paths:
  #     - path: /
  #       backend:
  #         serviceName: wordpress
  #         servicePort: 80
