{{- if .Values.ingress.enabled -}}
{{- $fullName := include "p2-wordpress-ingress-helm.fullname" . -}}
{{- $svcPort := .Values.module.wordpress.svc.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: wordpress-ing
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  # backend:
  #   serviceName: wordpress-svc
  #   servicePort: 80
  rules:
  - host: test1.com
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.module.wordpress.svc.name }}
          servicePort: {{ .Values.module.wordpress.svc.port }}
{{- end }}