apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.module.wordpress.svc.name }}
  labels:
    app: wordpress
spec:
  ports:
    - port: {{ .Values.module.wordpress.svc.port }}
  selector:
    app: wordpress
    tier: frontend
